export const START = "_START";
export const FAIL = "_FAIL";
export const SUCCESS = "_SUCCESS";

export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_DETAIL_MOVIE = "GET_DETAIL_MOVIE";
export const GET_SIMILAR_MOVIE = "GET_SIMILAR_MOVIE";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const NOW_IN_THE_CINEMA = "NOW_IN_THE_CINEMA";